spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-ffizwuhkmy64le96.mdb.yandexcloud.net:6432/solid-snake?&targetServerType=master&ssl=false
    username: postgres-user
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs