spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?&targetServerType=master&ssl=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs